apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: dashboard
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: dashboard
