apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: default
  labels:
    app: broker
spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      serviceAccountName: broker
      containers:
        - name: broker
          image: test
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: TIMESCALE_HOST
              value: test
            - name: TIMESCALE_USER
              value: "postgres"
            - name: TIMESCALE_PWD_ENV
              value: "TIMESCALE_PWD"
            - name: TIMESCALE_PWD
              value: test
            - name: OPCUA_SERVER_URL
              value: test
            - name: NAMESPACE_INDEX
              value: "3"
            - name: AUTO_ACCEPT_UNTRUSTED_SERVER_CERT
              value: "True"
            - name: MONITORED_NODE_IDENTIFIERS
              value: test
            - name: ENABLE_TIMESERIES_LOGGING
              value: "True"
          volumeMounts:
            - name: workload-token
              mountPath: /var/run/secrets/tokens
            - name: zta-svids
              mountPath: /var/run/secrets/svids
          resources: {}
      imagePullSecrets:
        - name: hestia-acr-secret
      volumes:
        - name: zta-svids
          emptyDir: {}
        - name: workload-token
          projected:
            sources:
              - serviceAccountToken:
                  path: workload
                  expirationSeconds: 7200
                  audience: test
