---
apiVersion: v1
kind: gatekeeper-system
metadata:
  name: hns-system 
  labels:
    istio-injection: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: gatekeeper
