---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hnc-system
  name: flux-applier
rules:
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier
  namespace: hnc-system
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: hnc-system
roleRef:
  kind: Role 
  name: flux-applier
  apiGroup: rbac.authorization.k8s.io
