apiVersion: v1
kind: Service
metadata:
  name: opcserver
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    app: server
