---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hns
  namespace: hns-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/kubernetes-sigs/hierarchical-namespaces      






